# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CRPS_score <- function(y, y_hat) {
    .Call('_JBU_CRPS_score', PACKAGE = 'JBU', y, y_hat)
}

energy_score <- function(y, y_hat, beta = 1) {
    .Call('_JBU_energy_score', PACKAGE = 'JBU', y, y_hat, beta)
}

variogram_score <- function(y, y_hat, p = .5) {
    .Call('_JBU_variogram_score', PACKAGE = 'JBU', y, y_hat, p)
}

