// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CRPS_score
arma::mat CRPS_score(arma::mat y, arma::cube y_hat);
RcppExport SEXP _JBU_CRPS_score(SEXP ySEXP, SEXP y_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type y_hat(y_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(CRPS_score(y, y_hat));
    return rcpp_result_gen;
END_RCPP
}
// energy_score
arma::vec energy_score(arma::mat y, arma::cube y_hat, double beta);
RcppExport SEXP _JBU_energy_score(SEXP ySEXP, SEXP y_hatSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type y_hat(y_hatSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(energy_score(y, y_hat, beta));
    return rcpp_result_gen;
END_RCPP
}
// variogram_score
arma::vec variogram_score(arma::mat y, arma::cube y_hat, double p);
RcppExport SEXP _JBU_variogram_score(SEXP ySEXP, SEXP y_hatSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type y_hat(y_hatSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(variogram_score(y, y_hat, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JBU_CRPS_score", (DL_FUNC) &_JBU_CRPS_score, 2},
    {"_JBU_energy_score", (DL_FUNC) &_JBU_energy_score, 3},
    {"_JBU_variogram_score", (DL_FUNC) &_JBU_variogram_score, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_JBU(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
