// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// JBU_norm_X_block
arma::mat JBU_norm_X_block(arma::mat X_block);
RcppExport SEXP _JBU_JBU_norm_X_block(SEXP X_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X_block(X_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(JBU_norm_X_block(X_block));
    return rcpp_result_gen;
END_RCPP
}
// JBU_filter
arma::umat JBU_filter(const arma::mat& X_block, const arma::mat& y_mx, const int& K);
RcppExport SEXP _JBU_JBU_filter(SEXP X_blockSEXP, SEXP y_mxSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_block(X_blockSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_mx(y_mxSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(JBU_filter(X_block, y_mx, K));
    return rcpp_result_gen;
END_RCPP
}
// JBU_X_alpha
arma::mat JBU_X_alpha(const arma::mat& X_block, const arma::mat& y_mx, const int& K);
RcppExport SEXP _JBU_JBU_X_alpha(SEXP X_blockSEXP, SEXP y_mxSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_block(X_blockSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_mx(y_mxSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(JBU_X_alpha(X_block, y_mx, K));
    return rcpp_result_gen;
END_RCPP
}
// JBU_sample
Rcpp::List JBU_sample(const arma::mat& X_block, const arma::mat& y_mx, const int& K, const bool RATS, double blocks, const bool suggest_blocks, const int iterations, const int burn, const int step_ahead, const bool post_par, const bool post_pred, const bool update_w, const bool use_given_delta, Rcpp::Nullable<Rcpp::NumericMatrix> given_delta_in, const double a_1, const double a_2, const bool do_sequential_filter);
RcppExport SEXP _JBU_JBU_sample(SEXP X_blockSEXP, SEXP y_mxSEXP, SEXP KSEXP, SEXP RATSSEXP, SEXP blocksSEXP, SEXP suggest_blocksSEXP, SEXP iterationsSEXP, SEXP burnSEXP, SEXP step_aheadSEXP, SEXP post_parSEXP, SEXP post_predSEXP, SEXP update_wSEXP, SEXP use_given_deltaSEXP, SEXP given_delta_inSEXP, SEXP a_1SEXP, SEXP a_2SEXP, SEXP do_sequential_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_block(X_blockSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_mx(y_mxSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const bool >::type RATS(RATSSEXP);
    Rcpp::traits::input_parameter< double >::type blocks(blocksSEXP);
    Rcpp::traits::input_parameter< const bool >::type suggest_blocks(suggest_blocksSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type step_ahead(step_aheadSEXP);
    Rcpp::traits::input_parameter< const bool >::type post_par(post_parSEXP);
    Rcpp::traits::input_parameter< const bool >::type post_pred(post_predSEXP);
    Rcpp::traits::input_parameter< const bool >::type update_w(update_wSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_given_delta(use_given_deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type given_delta_in(given_delta_inSEXP);
    Rcpp::traits::input_parameter< const double >::type a_1(a_1SEXP);
    Rcpp::traits::input_parameter< const double >::type a_2(a_2SEXP);
    Rcpp::traits::input_parameter< const bool >::type do_sequential_filter(do_sequential_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(JBU_sample(X_block, y_mx, K, RATS, blocks, suggest_blocks, iterations, burn, step_ahead, post_par, post_pred, update_w, use_given_delta, given_delta_in, a_1, a_2, do_sequential_filter));
    return rcpp_result_gen;
END_RCPP
}
// CRPS_score
arma::mat CRPS_score(arma::mat y, arma::cube y_hat);
RcppExport SEXP _JBU_CRPS_score(SEXP ySEXP, SEXP y_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type y_hat(y_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(CRPS_score(y, y_hat));
    return rcpp_result_gen;
END_RCPP
}
// energy_score
arma::vec energy_score(arma::mat y, arma::cube y_hat, double beta);
RcppExport SEXP _JBU_energy_score(SEXP ySEXP, SEXP y_hatSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type y_hat(y_hatSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(energy_score(y, y_hat, beta));
    return rcpp_result_gen;
END_RCPP
}
// variogram_score
arma::vec variogram_score(arma::mat y, arma::cube y_hat, double p);
RcppExport SEXP _JBU_variogram_score(SEXP ySEXP, SEXP y_hatSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type y_hat(y_hatSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(variogram_score(y, y_hat, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JBU_JBU_norm_X_block", (DL_FUNC) &_JBU_JBU_norm_X_block, 1},
    {"_JBU_JBU_filter", (DL_FUNC) &_JBU_JBU_filter, 3},
    {"_JBU_JBU_X_alpha", (DL_FUNC) &_JBU_JBU_X_alpha, 3},
    {"_JBU_JBU_sample", (DL_FUNC) &_JBU_JBU_sample, 17},
    {"_JBU_CRPS_score", (DL_FUNC) &_JBU_CRPS_score, 2},
    {"_JBU_energy_score", (DL_FUNC) &_JBU_energy_score, 3},
    {"_JBU_variogram_score", (DL_FUNC) &_JBU_variogram_score, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_JBU(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
