# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
JBU_norm_X_block <- function(X_block) {
    .Call(`_JBU_JBU_norm_X_block`, X_block)
}

#' @export
JBU_filter <- function(X_block, y_mx, K) {
    .Call(`_JBU_JBU_filter`, X_block, y_mx, K)
}

#' @export
JBU_X_alpha <- function(X_block, y_mx, K) {
    .Call(`_JBU_JBU_X_alpha`, X_block, y_mx, K)
}

#' @export
JBU_sample <- function(X_block, y_mx, K, RATS = TRUE, blocks = 1, suggest_blocks = FALSE, iterations = 1000L, burn = 200L, step_ahead = 4L, post_par = TRUE, post_pred = TRUE, update_w = TRUE, use_given_delta = FALSE, given_delta_in = NULL, a_1 = 5, a_2 = 50, do_sequential_filter = FALSE) {
    .Call(`_JBU_JBU_sample`, X_block, y_mx, K, RATS, blocks, suggest_blocks, iterations, burn, step_ahead, post_par, post_pred, update_w, use_given_delta, given_delta_in, a_1, a_2, do_sequential_filter)
}

#' @export
CRPS_score <- function(y, y_hat) {
    .Call(`_JBU_CRPS_score`, y, y_hat)
}

#' @export
energy_score <- function(y, y_hat, beta = 1) {
    .Call(`_JBU_energy_score`, y, y_hat, beta)
}

#' @export
variogram_score <- function(y, y_hat, p = .5) {
    .Call(`_JBU_variogram_score`, y, y_hat, p)
}

