# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Normalize a predictor block
#'
#' Centers and scales each column of `X_block`. Columns with non-zero
#' standard deviation are divided by their standard deviation. Columns with
#' zero standard deviation are centered only.
#'
#' @param X_block A numeric matrix of predictors.
#'
#' @return A numeric matrix with the same dimensions as `X_block`, where each
#' column has been centered and, when possible, scaled.
#'
#' @examples
#' X_block <- matrix(1:12, nrow = 4)
#' JBU_norm_X_block(X_block)
#'
#' @export
JBU_norm_X_block <- function(X_block) {
    .Call(`_JBU_JBU_norm_X_block`, X_block)
}

#' Select predictors for each series
#'
#' Applies the JBU filtering step to select the `K` most relevant predictors
#' from `X_block` for each series in `y_mx`.
#'
#' @param X_block A numeric matrix of candidate predictors.
#' @param y_mx A numeric matrix of observed series. Rows are time points and
#' columns are series.
#' @param K An integer giving the number of predictors to select for each series.
#'
#' @return An integer matrix with `K` rows and one column for each series in
#' `y_mx`. Each column contains the selected predictor indices.
#'
#' @examples
#' set.seed(1)
#' X_block <- matrix(rnorm(40), nrow = 10, ncol = 4)
#' y_mx <- cbind(
#'   2 * X_block[, 1] + rnorm(10, sd = 0.1),
#'   -1 * X_block[, 3] + rnorm(10, sd = 0.1)
#' )
#'
#' JBU_filter(X_block, y_mx, K = 2)
#'
#' @export
JBU_filter <- function(X_block, y_mx, K) {
    .Call(`_JBU_JBU_filter`, X_block, y_mx, K)
}

#' Build the filtered predictor matrix
#'
#' Applies the JBU filter and constructs the block-diagonal predictor matrix
#' used by the sampler.
#'
#' @param X_block A numeric matrix of candidate predictors.
#' @param y_mx A numeric matrix of observed series. Rows are time points and
#' columns are series.
#' @param K An integer giving the number of predictors to select for each series.
#'
#' @return A numeric matrix containing the filtered block-diagonal predictor
#' structure. If `X_block` has `T` rows, `y_mx` has `M` columns, and `K`
#' predictors are selected per series, the result has `T * M` rows and
#' `K * M` columns.
#'
#' @examples
#' set.seed(1)
#' X_block <- matrix(rnorm(40), nrow = 10, ncol = 4)
#' y_mx <- cbind(
#'   2 * X_block[, 1] + rnorm(10, sd = 0.1),
#'   -1 * X_block[, 3] + rnorm(10, sd = 0.1)
#' )
#'
#' X_alpha <- JBU_X_alpha(X_block, y_mx, K = 2)
#' dim(X_alpha)
#' X_alpha
#'
#' @export
JBU_X_alpha <- function(X_block, y_mx, K) {
    .Call(`_JBU_JBU_X_alpha`, X_block, y_mx, K)
}

#' @export
JBU_sample <- function(X_block, y_mx, K, RATS = TRUE, blocks = 1, suggest_blocks = FALSE, iterations = 1000L, burn = 200L, step_ahead = 4L, post_par = TRUE, post_pred = TRUE, update_w = TRUE, use_given_delta = FALSE, given_delta_in = NULL, a_1 = 5, a_2 = 50, do_sequential_filter = FALSE) {
    .Call(`_JBU_JBU_sample`, X_block, y_mx, K, RATS, blocks, suggest_blocks, iterations, burn, step_ahead, post_par, post_pred, update_w, use_given_delta, given_delta_in, a_1, a_2, do_sequential_filter)
}

#' Compute the continuous ranked probability score
#'
#' Computes the continuous ranked probability score (CRPS) for each forecast
#' horizon and series, comparing observed values with simulated forecast samples.
#'
#' @param y A numeric matrix of observed values. Rows are forecast horizons and
#' columns are series.
#' @param y_hat A numeric array of forecast samples with dimensions
#' samples x series x horizons.
#'
#' @return A numeric matrix with the same dimensions as `y`, containing one CRPS
#' value for each horizon and series.
#'
#' @examples
#' set.seed(1)
#' y <- matrix(c(10, 12, 20, 22), nrow = 2, ncol = 2)
#' y_hat <- array(rnorm(5 * 2 * 2, mean = 15, sd = 2), dim = c(5, 2, 2))
#'
#' CRPS_score(y, y_hat)
#'
#' @export
CRPS_score <- function(y, y_hat) {
    .Call(`_JBU_CRPS_score`, y, y_hat)
}

#' Compute the energy score
#'
#' Computes the energy score for multivariate probabilistic forecasts at each
#' forecast horizon.
#'
#' @param y A numeric matrix of observed values. Rows are forecast horizons and
#' columns are series.
#' @param y_hat A numeric array of forecast samples with dimensions
#' samples x series x horizons.
#' @param beta A numeric power parameter. The default is `1`.
#'
#' @return A numeric vector with one energy score for each forecast horizon.
#'
#' @examples
#' set.seed(1)
#' y <- matrix(c(10, 12, 20, 22), nrow = 2, ncol = 2)
#' y_hat <- array(rnorm(5 * 2 * 2, mean = 15, sd = 2), dim = c(5, 2, 2))
#'
#' energy_score(y, y_hat)
#'
#' @export
energy_score <- function(y, y_hat, beta = 1) {
    .Call(`_JBU_energy_score`, y, y_hat, beta)
}

#' Compute the variogram score
#'
#' Computes the variogram score for multivariate probabilistic forecasts at
#' each forecast horizon.
#'
#' @param y A numeric matrix of observed values. Rows are forecast horizons and
#' columns are series.
#' @param y_hat A numeric array of forecast samples with dimensions
#' samples x series x horizons.
#' @param p A numeric power parameter. The default is `0.5`.
#'
#' @return A numeric vector with one variogram score for each forecast horizon.
#'
#' @examples
#' set.seed(1)
#' y <- matrix(c(10, 12, 20, 22), nrow = 2, ncol = 2)
#' y_hat <- array(rnorm(5 * 2 * 2, mean = 15, sd = 2), dim = c(5, 2, 2))
#'
#' variogram_score(y, y_hat)
#'
#' @export
variogram_score <- function(y, y_hat, p = .5) {
    .Call(`_JBU_variogram_score`, y, y_hat, p)
}

